// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL6dF7JSmDwlsgDgiE1LIGhRwyrcsmV5A',
    appId: '1:922872147634:web:da8bc6a23a4c44e16a23ab',
    messagingSenderId: '922872147634',
    projectId: 'light-electrum',
    authDomain: 'light-electrum.firebaseapp.com',
    storageBucket: 'light-electrum.firebasestorage.app',
    measurementId: 'G-J464BT5KHJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOAdKy2p-Zl7CtJ4UUUQOza8XogDVu45o',
    appId: '1:922872147634:android:eeed3cccb54035966a23ab',
    messagingSenderId: '922872147634',
    projectId: 'light-electrum',
    storageBucket: 'light-electrum.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMILnXUspEEKCrwGkatrxK5Y8aiz6WYIM',
    appId: '1:922872147634:ios:4c1df46ed53cd5836a23ab',
    messagingSenderId: '922872147634',
    projectId: 'light-electrum',
    storageBucket: 'light-electrum.firebasestorage.app',
    iosBundleId: 'com.example.lightweightElectrum',
  );

}